---
dist: bionic
language: minimal

cache:
  directories:
    - /home/travis/.vagrant.d/boxes

jobs:
  include:

    - stage: build
      install:
        - sudo apt-get update && sudo apt-get install -y bridge-utils dnsmasq-base ebtables libvirt-bin libvirt-dev qemu-kvm qemu-utils ruby-dev
        - sudo wget -nv https://releases.hashicorp.com/vagrant/2.2.9/vagrant_2.2.9_x86_64.deb
        - sudo dpkg -i vagrant_2.2.9_x86_64.deb
        - sudo vagrant plugin install vagrant-libvirt vagrant-scp vagrant-reload
      script:
        - travis_wait sudo vagrant up --provider=libvirt flutterbox
        - travis_wait sudo vagrant ssh flutterbox -- sudo salt-call state.highstate
        - travis_wait sudo vagrant reload
        - travis_wait sudo vagrant ssh flutterbox -- sudo salt-call state.sls android-studio
        - travis_wait sudo vagrant ssh flutterbox -- sudo salt-call state.sls flutter
        - travis_wait sudo vagrant ssh flutterbox -- sudo salt-call state.sls myapps
        - sudo vagrant destroy --force flutterbox

    - stage: release
      install:
        - wget https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh
        - sudo bash install.sh
        - nvm install lts/*
        - npm i -D semantic-release @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/changelog @semantic-release/npm @semantic-release/github @semantic-release/git @semantic-release/exec @commitlint/cli @commitlint/config-conventional
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
        on:
          all_branches: true 

notifications:
  slack:
    secure: snIhQH/tWG5hzqQd6dKDkJlC9Q5qkp6Lntu6Hycsktz0DXc43vVp+QmZeXVWnriFMdg42tsLpM4x5pQIvvx9/5OzYYWCMgBBVwBGaJ6LvVydJTtrXRIcjlAGNCy9YapiHE4PHReMAkAtEctQX2hCT80n1IP8p5cEICEPcrylk1DNEqM98m7bneyLOj2J+d7V7AABwUP3pEcN4KeAXStIQK848Kpsl+LHnCihodUKYadkrFOiTwbIL2ODwLeGEoELrqXsmwv5betP7lka0xlQ+wtPharjJ34AjpaDhOj75EuMykZVGk+4cKiCqXy14o+w1kbb2/DgXg1DnFQmosUSuhSTztAU7joELdwDsEcLUjk1Eep8uUbYOX7fwid33qf9kekc/eFg89dbf1nIxnRuCIz4WO3+SzRB27vIyz+Lg39WLK2Gx96vLbeH0FjTRM96BOljAZQlPOBDEomgdPcHlVGAATZEgJQ418Nf7sM+LHx3T2cdD1m71Ks+ckTMA6T9Q5rmmw/Uk+voXJJ+yxJiUsPv4ktQupb+QoZZ3R9VCiR6L9GfyZmdgS+PFwER+4WHKe266kH2QA7tfbCvhjdIYPl9fWmUP1KVU3vVgxmBWulITHl277037B3pzkmbt789K9iDfpNVTiWV5IArdiM9qC6Rt1M3REGNdShs9AnGczM=
